r"""LaTeX macros renderer.

Writes one ``\newcommand`` per claim. Macro names are auto-slugged from
claim names (LaTeX forbids digits in control sequences, so digits are
spelled out).
"""

from __future__ import annotations

import re
from pathlib import Path

from corroborate.claims import Claim, ClaimValue


_MACRO_TOKEN_RE = re.compile(r"[A-Za-z0-9]+")
_DIGIT_WORDS = {
    "0": "zero", "1": "one", "2": "two", "3": "three", "4": "four",
    "5": "five", "6": "six", "7": "seven", "8": "eight", "9": "nine",
}


def _spell_digits(s: str) -> str:
    return "".join(_DIGIT_WORDS.get(c, c) for c in s)


def name_to_macro(name: str) -> str:
    """Slugify a claim name into a LaTeX control sequence.

    Rules:
      - Strip apostrophes so "Cohen's" stays one token.
      - Split on any non-alphanumeric character.
      - Lowercase each token.
      - Spell out every digit ("phase1" -> "phaseone").
      - First token stays lowercase; subsequent tokens are capitalized
        (camelCase). All-caps acronyms normalise: "CREAK" -> "creak".
    """
    stripped = name.replace("'", "").replace("’", "")
    tokens = _MACRO_TOKEN_RE.findall(stripped)
    if not tokens:
        raise ValueError(f"Claim name has no alphanumeric content: {name!r}")
    pieces: list[str] = []
    for i, tok in enumerate(tokens):
        low = _spell_digits(tok.lower())
        if i == 0:
            piece = low
        else:
            piece = low[0].upper() + low[1:]
        pieces.append(piece)
    return "".join(pieces)


def _format_value(value) -> str:
    if isinstance(value, bool):
        return str(value)
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return f"{value:g}"
    return str(value)


def _tex_escape(s: str) -> str:
    return s.replace("\\", "\\textbackslash{}").replace("%", "\\%")


def _cap_first(s: str) -> str:
    return s[:1].upper() + s[1:] if s else s


def _iter_leaf_macros(claim_name: str, value):
    """Yield (macro_slug, scalar_value, comment_suffix) for each leaf cell.

    - Scalar: one yield with empty comment_suffix.
    - Row dict: one yield per key.
    - Table (dict-of-dicts): one yield per (row_key, col_key).
    """
    base = name_to_macro(claim_name)
    if not isinstance(value, dict):
        yield base, value, ""
        return
    any_value = next(iter(value.values()))
    is_table = isinstance(any_value, dict)
    if not is_table:
        for col_key, cell in value.items():
            yield base + _cap_first(name_to_macro(col_key)), cell, f".{col_key}"
        return
    for row_key, inner in value.items():
        row_seg = _cap_first(name_to_macro(row_key))
        for col_key, cell in inner.items():
            col_seg = _cap_first(name_to_macro(col_key))
            yield base + row_seg + col_seg, cell, f".{row_key}.{col_key}"


def write_numbers_tex(
    claims: list[Claim],
    path: Path | str,
    *,
    header: str = (
        "% Auto-generated by corroborate. Do not edit by hand.\n"
        "% Each macro's value comes from a claim sidecar.\n"
    ),
) -> None:
    r"""Emit ``\newcommand{\macroName}{value}`` for every claim (and every cell of table claims)."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [header.rstrip("\n"), ""]
    macros_seen: dict[str, str] = {}
    for c in claims:
        for macro, leaf, suffix in _iter_leaf_macros(c.name, c.value):
            if macro in macros_seen:
                raise ValueError(
                    f"Macro collision: {macro!r} from {c.name + suffix!r} conflicts with "
                    f"{macros_seen[macro]!r}"
                )
            macros_seen[macro] = c.name + suffix
            body = _format_value(leaf)
            lines.append(f"% {_tex_escape(c.name + suffix)}")
            lines.append(f"\\newcommand{{\\{macro}}}{{{body}}}")
    path.write_text("\n".join(lines) + "\n")
