"""Markdown audit-surface renderer.

Produces a flat table: the registry rendered as rows for humans and agents.
"""

from __future__ import annotations

from pathlib import Path

from corroborate.claims import Claim, ClaimValue


def _format_value(value: ClaimValue) -> str:
    if isinstance(value, bool):
        return str(value)
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return f"{value:g}"
    return str(value)


def _md_escape(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ")


def write_claims_md(
    claims: list[Claim],
    path: Path | str,
    *,
    title: str = "Claims registry",
) -> None:
    """Emit a markdown audit table.

    Columns: Name | Value | Statement | Source | Computed | Used in | Derivation
    (data_paths is rendered inline with the derivation cell.)
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# {title}",
        "",
        "Auto-generated by corroborate. Each row is a single numeric claim.",
        f"Total claims: **{len(claims)}**",
        "",
        "| Name | Value | Statement | Source | Computed | Used in | Derivation |",
        "|---|---|---|---|---|---|---|",
    ]
    for c in sorted(claims, key=lambda c: c.name.lower()):
        used = ", ".join(c.used_in) if c.used_in else ""
        value_str = _format_value(c.value)
        statement = _md_escape(c.statement)
        derivation_parts: list[str] = []
        if c.derivation:
            derivation_parts.append(_md_escape(c.derivation))
        if c.data_paths:
            paths = ", ".join(f"`{p}`" for p in c.data_paths)
            derivation_parts.append(f"inputs: {paths}")
        derivation_cell = "<br>".join(derivation_parts)
        lines.append(
            f"| `{c.name}` | {value_str} | {statement} | `{c.source}` | "
            f"{c.computed_at} | {used} | {derivation_cell} |"
        )
    path.write_text("\n".join(lines) + "\n")
